opt_out_usage
fastlane_version "1.23.0"
default_platform :ios


platform :ios do
  before_all do
    increment_build_number
    gym(scheme: "RNPlayNative")
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    deliver(beta: true)
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    sigh
    deliver(skip_deploy: true, force: true)
    # frameit
  end
end
